@startuml
title General Authorisation Model

class Authorisation {
 +dct:identifier : uri
 *dct:title : Literal
 *hasOwner :
 +hasLegalBasisIn :
 +isWitnessedBy :
 *principal :
 +status : ENUM [active, inactive]
 *dateOfIssue : date
 *dct:temporal :
 +type : Skos Concept
 'type is optional, just in case property. 
 +replaces :
 +delegable : [Y/N]
 *hasRule :
 +seeAlso : uri
 +hasScope :
}

class AssignmentRule {
 *grantee :
 *jointType : ENUM [Alone, All, Majority,
 One of y, At Least x of y]
 *totalNumberOfGranteesInRule : Integer
 +and:
 +or:
}

class [ABS]LegalBasis {
' Legal Basis is a Role that the law or an other
' authorisation gan give.
 *code : string
 *name : string
}

class Law {
 *jurisdiction : string
 *code : string
 *name : string
}

class PeriodOfTime {
 *startDate : date
 +endDate : date
}


class IdentificationDocument {
 *number : string
 *name : string
 +type :
}

class Involvement {
 +code : string
 *name : string
 *member :
 *inOrganisation :
 +hasRole :
}

class Machine {
 *id : url
 +name : string
}

class Person {
 *nameFirst : string
 *nameLast : string
 +dateOfBirth : date
 +placeOfBirth :
 +fullAdress :
 +identificationDocument :
}

class Role {
 *name :
 *inOrganisation :
}

class Restriction {
 +title : string
 +value : string
 +unit : string
 +source : uri
 'the source points to the code, not the code list..
 'make as much restrictions as you need to define the scope.
 }

class CodeList:Financial
{
 *amount : float
 +currency : ENUM [EUR,
 NOK, SEK, ...]
}

class CodeList:NACE
{
 *code:
 *ENUM : [A Agriculture,
 Forestry and Fishing]
}

class CodeList:identificationDocumentType
{
 *code:
 *ENUM : [passport, ID card]
}

class CodeList:eService
{
 *code:
 *ENUM : [Buy, Sell,
 Pay, Issue, Decide]
}

class CodeList:SpacialExtent
{
 *code
 *ENUM : [State,
 Province, Municipality]
}

class  EconomicOperator
{
 *legalName : string
 +registryNumber : string
 *EUID : identifier
 pattern : "^[A-Z]{2}[A-Z]{3}\\.
 [a-zA-Z0-9]+\\.[a-zA-Z0-9]+$"
}

class Scope {
 *title : string
 +hasRestriction :[operator in subproperty]
}

class Entity {
 *mandatory
 +optional
}

Authorisation::principal "1" -left-> "1..n" Involvement #line:DarkRed;text:White :_____
Authorisation::isWitnessedBy "1" -up-> "0..n" Involvement__ #line:DarkRed;text:DarkRed
Authorisation::hasLegalBasisIn "1" -up-> "0..n" [ABS]LegalBasis #line:DarkRed;text:DarkRed
Authorisation::hasScope "1" -down-> "0..n" Scope #line:DarkRed;text:DarkRed
Authorisation::seeAlso "1" -down-> "0..1" Document #line:DarkRed;text:DarkRed
Authorisation::hasRule "1" -right-> "1" AssignmentRule #line:DarkRed;text:White :_____
Authorisation::temporal "1" -left-> "1" PeriodOfTime #line:DarkRed;text:White :_____
Authorisation::hasOwner "1" -up-> "1" EconomicOperator__ #line:DarkRed;text:White :_____

skinparam groupInheritance 2
_Role  <|-- [ABS]LegalBasis_ #line:DarkRed;text:White :_____

[ABS]LegalBasis_  <|-- Law #line:DarkRed;text:White :_____
[ABS]LegalBasis_  <|-- Authorisation_ #line:DarkRed;text:White :_____


AssignmentRule::isAssignedTo "1" -right-> "1..n" Involvement_ #line:DarkRed;text:DarkRed
AssignmentRule::and "1" -down-> "0..n" AssignmentRule__ #line:DarkRed;text:DarkRed
AssignmentRule::or "1" -down-> "0..n" AssignmentRule_ #line:DarkRed;text:DarkRed

Involvement::hasRole "1" -down-> "0..1" Role #line:DarkRed;text:DarkRed
Involvement::member "1" -down-> "0..1" Person  #line:DarkRed;text:DarkRed
Involvement::member "1" -down-> "0..1" Machine  #line:DarkRed;text:DarkRed
Involvement::inOrganisation "1" -down-> "0..1" EconomicOperator  #line:DarkRed;text:DarkRed
Involvement_::hasRole "1" -down-> "0..1" Role_ #line:DarkRed;text:DarkRed
Involvement_::member "1" -down-> "0..1" Person_  #line:DarkRed;text:DarkRed
Involvement_::member "1" -down-> "0..1" Machine_  #line:DarkRed;text:DarkRed
Involvement_::inOrganisation "1" -down-> "0..1" EconomicOperator_  #line:DarkRed;text:DarkRed

Restriction::source .down.> "CodeList:NACE::code" #line:Gray;text:DarkRed
Restriction::source .down.> "CodeList:eService::code" #line:Gray;text:DarkRed
Restriction::source .down.> "CodeList:EconomicOperator" #line:Gray;text:DarkRed
Restriction::source .down.> "CodeList:SpacialExtent::code" #line:Gray;text:DarkRed
Restriction::source .down.> "CodeList:Financial::code" #line:Gray;text:DarkRed
Person::identificationDocument -down-> IdentificationDocument
IdentificationDocument::type .right.> "CodeList:identificationDocumentType::code" #line:Gray;text:DarkRed

Role::inOrganisation -left-> "EconomicOperator" #line:DarkRed;text:DarkRed

Scope::hasRestriction "1" -down-> "0..n" Restriction #line:DarkRed;text:DarkRed

AssignmentRule -down-> Document #line:White
Role -right- Person #line:White
'Person -right- Machine #line:White
Role -left- Person #line:White
EconomicOperator__ -left- Involvement__ #line:White
EconomicOperator -left- Person #line:White
Involvement -right- PeriodOfTime #line:White
AssignmentRule_ -right- AssignmentRule__ #line:White
Entity -right- _Role #line:White


class Authorisation #LightYellow;line:DarkRed;text:DarkRed
class Law #LightYellow;line:DarkRed;text:DarkRed
class Scope #LightYellow;line:DarkRed;text:DarkRed
class Document #LightYellow;line:DarkRed;text:DarkRed
class [ABS]LegalBasis #LightYellow;line:DarkRed;text:DarkRed
class IdentificationDocument #LightYellow;line:DarkRed;text:DarkRed
class EconomicOperator #LightYellow;line:DarkRed;text:DarkRed
class Involvement #LightYellow;line:DarkRed;text:DarkRed
class Role #LightYellow;line:DarkRed;text:DarkRed
class Person #LightYellow;line:DarkRed;text:DarkRed
class Machine #LightYellow;line:DarkRed;text:DarkRed
class AssignmentRule #LightYellow;line:DarkRed;text:DarkRed
class Restriction #LightYellow;line:DarkRed;text:DarkRed
class Entity #LightYellow;line:DarkRed;text:DarkRed
class PeriodOfTime #LightYellow;line:DarkRed;text:DarkRed
class CodeList:eService #CEEED0;line:285F17;text:285F17
class CodeList:Financial #CEEED0;line:285F17;text:285F17
class CodeList:NACE #CEEED0;line:285F17;text:285F17
class CodeList:SpacialExtent #CEEED0;line:285F17;text:285F17
class CodeList:identificationDocumentType #CEEED0;line:285F17;text:285F17

hide circle

@enduml
