@startuml
title General Authorisation Model

class Authorisation {
 +dct:identifier : uri
 *dct:title : Literal
 *entityConcerned :
 +isWitnessedBy :
 +hasLegalBasisIn :
 *principal :
 +status : ENUM [active, inactive]
 *dateOfIssue : date
 *dct:temporal :
 +type : Skos Concept
 'type is optional, just in case property. 
 +replaces :
 +delegable : [Y/N]
 *hasRule :
 +isDocumentedIn : uri
 +hasScope :
}

class AssignmentRule {
 *grantee :
 *jointType : ENUM [Alone, All, Majority,
 One of y, At Least x of y]
 *totalNumberOfGranteesInRule : Integer
 +and:
 +or:
}

class [ABS]LegalBasis {
' Legal Basis is a Role that the law or an other
' authorisation gan give.
}

class Law {
 *jurisdiction : string
 *code : string
 *name : string
}

class PeriodOfTime {
 *startDate : date
 +endDate : date
}


class IdentificationDocument {
 *number : string
 *name : string
 +type :
}

class Involvement {
 +code : string
 *name : string
 *member :
 *inOrganisation :
 +hasRole :
}

class Machine {
 *id : url
 +name : string
}

class Person {
 *nameFirst : string
 *nameLast : string
 +dateOfBirth : date
 +placeOfBirth :
 +fullAdress :
 +identificationDocument :
}

class Role {
 *name :
 *inOrganisation :
}

class Restriction {
 *operator : ISO80000-2
 *value : NumericValue
 *unit : Unit
 +source : uri
 'the source points to the code, not the code list..
 'make as much restrictions as you need to define the scope.
 }
 
class Unit {
 *exponent : NumericValue
 *unit : Unit
 }

class "DataType:NumericValue\n<size:11><color:gray><i>Allowed numeric value types.</i></color></size>" as NumericValue{
  <font:monospaced><color:gray>type      example  definition</color></font>
  --
  <font:monospaced>integer   -2       whole number</font>
  <font:monospaced>decimal   3.14     exact decimal value</font>
  <font:monospaced>rational  1/3      exact fraction</font>
}

class "CodeList:ISO80000Unit\n<size:11><color:gray><i>Scientific unit symbols based on ISO/IEC 80000.</i></color></size>" as ISO80000Unit {
  <font:monospaced><color:gray>symbol  definition</color></font>
  --
  <font:monospaced>m       metre</font>
  <font:monospaced>s       second</font>
  <font:monospaced>kg      kilogram</font>
  <font:monospaced>N       newton</font>
  <font:monospaced>Pa      pascal</font>
  <font:monospaced>J       joule</font>
  <font:monospaced>W       watt</font>
}

class "CodeList:ISO80000-2\n<size:11><color:gray><i>Allowed operators for expressions and constraints.</i></color></size>" as ISO80000-2 {
  <font:monospaced><color:gray>code   symbol  definition</color></font>
  --
  <font:monospaced>ADD    +       addition</font>
  <font:monospaced>SUB    -       subtraction</font>
  <font:monospaced>MUL    *       multiplication</font>
  <font:monospaced>DIV    /       division</font>
  <font:monospaced>EQ     =       equal to</font>
  <font:monospaced>NEQ    !=      not equal to</font>
  <font:monospaced>LT     <       less than</font>
  <font:monospaced>LTE    <=      less than or equal to</font>
  <font:monospaced>GT     >       greater than</font>
  <font:monospaced>GTE    >=      greater than or equal to</font>
  <font:monospaced>AND    AND     logical conjunction</font>
  <font:monospaced>OR     OR      logical disjunction</font>
  <font:monospaced>NOT    NOT     logical negation</font>
}

class "CodeList:ISO4217:20215\n<size:11><color:gray><i>Allowed currency values.</i></color></size>" as ISO4217:20215 {
  <font:monospaced><color:gray>code  definition</color></font>
  --
  <font:monospaced>EUR   Euro</font>
  <font:monospaced>USD   United States Dollar</font>
  <font:monospaced>NOK   Norwegian krone</font>
  <font:monospaced>GBP   Pound sterling</font>
}

class "CodeList:NACE\n<size:11><color:gray><i>Allowed economic activity codes based on NACE.</i></color></size>" as NACE {
  <font:monospaced><color:gray>code   definition</color></font>
  --
  <font:monospaced>01.11  Growing of cereals, leguminous crops and oil seeds</font>
  <font:monospaced>62.01  Computer programming activities</font>
  <font:monospaced>64.19  Other monetary intermediation</font>
}

class "CodeList:identificationDocumentType\n<size:11><color:gray><i>Document types aligned with ICAO Doc 9303 MRTD categories.</i></color></size>" as identificationDocumentType {
  <font:monospaced><color:gray>code      definition</color></font>
  --
  <font:monospaced>PASSPORT  Machine readable passport</font>
  <font:monospaced>ID_CARD   Machine readable official travel document</font>
  <font:monospaced>VISA      Machine readable visa</font>
  <font:monospaced>EMERGENCY Emergency travel document</font>
}
class "CodeList:eService\n<size:11><color:gray><i>Allowed eService codes based on service provider.</i></color></size>" as eService {
  <font:monospaced><color:gray>code   definition</color></font>
  --
  <font:monospaced>2026.Q2  stating 2026 Q3 VAT</font>
  <font:monospaced>2026     stating 2026 revenue</font>
  <font:monospaced>ALL      state all taxex</font>
}


class "CodeList:SpacialExtent\n<size:11><color:gray><i>Allowed regions codes based on\n<size:11><color:gray><i>several ISO's or online published lists.</i></color></size>" as SpacialExtent {
  <font:monospaced><color:gray>code   definition</color></font>
  --
  <font:monospaced>NL  Netherlands (ISO3166-1 alpha2)</font>
  <font:monospaced>FR  Friesland (GIS standard)</font>
}

class  EconomicOperator
{
 *legalName : string
 +registryNumber : string
 *EUID : identifier
 pattern : "^[A-Z]{2}[A-Z]{3}\\.
 [a-zA-Z0-9]+\\.[a-zA-Z0-9]+$"
}

class Scope {
 *title : string
 +hasRestriction :[operator in subproperty]
}

class Entity {
 *mandatory
 +optional
}

Authorisation::principal "1" -left-> "1..n" Involvement #line:DarkRed;text:White :_____
Authorisation::isWitnessedBy "0..1" -up-> "1..n" Involvement__ #line:DarkRed;text:DarkRed
Authorisation::hasLegalBasisIn "1" -up-> "1..n" [ABS]LegalBasis #line:DarkRed;text:DarkRed
Authorisation::hasScope "0..1" -down-> "1..n" Scope #line:DarkRed;text:DarkRed
Authorisation::isDocumentedIn "0..1" -down-> "1..n" Document #line:DarkRed;text:DarkRed
Authorisation::hasRule "1" -right-> "1" AssignmentRule #line:DarkRed;text:White :_____
Authorisation::temporal "1" -left-> "1" PeriodOfTime #line:DarkRed;text:White :_____
Authorisation::entityConcerned "1" -up-> "1..n" EconomicOperator__ #line:DarkRed;text:White :_____

skinparam groupInheritance 2
_Role  <|-- [ABS]LegalBasis_ #line:DarkRed;text:White :_____

NumericValue -down- ISO80000Unit #line:White;text:White :_____

[ABS]LegalBasis_  <|-- Law #line:DarkRed;text:White :_____
[ABS]LegalBasis_  <|-- By'Law #line:DarkRed;text:White :_____
[ABS]LegalBasis_  <|-- Authorisation_ #line:DarkRed;text:White :_____


AssignmentRule::isAssignedTo "1" -right-> "1..n" Involvement_ #line:DarkRed;text:DarkRed
AssignmentRule::and "1" -down-> "0..n" AssignmentRule__ #line:DarkRed;text:DarkRed
AssignmentRule::or "1" -down-> "0..n" AssignmentRule_ #line:DarkRed;text:DarkRed

Involvement::hasRole "1" -down-> "0..1" Role #line:DarkRed;text:DarkRed
Involvement::member "1" -down-> "0..1" Person  #line:DarkRed;text:DarkRed
Involvement::member "1" -down-> "0..1" Machine  #line:DarkRed;text:DarkRed
Involvement::inOrganisation "1" -down-> "0..1" EconomicOperator  #line:DarkRed;text:DarkRed
Involvement_::hasRole "1" -down-> "0..1" Role_ #line:DarkRed;text:DarkRed
Involvement_::member "1" -down-> "0..1" Person_  #line:DarkRed;text:DarkRed
Involvement_::member "1" -down-> "0..1" Machine_  #line:DarkRed;text:DarkRed
Involvement_::inOrganisation "1" -down-> "0..1" EconomicOperator_  #line:DarkRed;text:DarkRed

Restriction::operator "1" .left.> "1" "ISO80000-2" #line:Gray;text:DarkRed
Restriction::value "1" .right.> "1" "NumericValue::type" #line:Gray;text:DarkRed
Restriction::unit "1" .right.> "n" "Unit" #line:Gray;text:DarkRed
Unit::exponent .up.> "NumericValue::type" #line:Gray;text:White :_
Unit::unit "1" .down.> "1..n" "ISO4217:20215::code" #line:Gray;text:DarkRed
Unit::unit "1" .right.> "1..n" "ISO80000Unit::exponent" #line:Gray;text:White :__

Restriction::source .down.> "NACE::code" #line:Gray;text:DarkRed
Restriction::source .down.> "eService::code" #line:Gray;text:DarkRed
Restriction::source .down.> "SpacialExtent::code" #line:Gray;text:DarkRed
Person::identificationDocument -down-> IdentificationDocument
IdentificationDocument::type .right.> "identificationDocumentType::code" #line:Gray;text:DarkRed

Role::inOrganisation -left-> "EconomicOperator" #line:DarkRed;text:DarkRed

Scope::hasRestriction "1" -down-> "0..n" Restriction #line:DarkRed;text:DarkRed

AssignmentRule -down-> Document #line:White
Role -right- Person #line:White
"ISO4217:20215" -up- ISO80000Unit #line:White
Role -left- Person #line:White
EconomicOperator__ -left- Involvement__ #line:White
EconomicOperator -left- Person #line:White
Involvement -right- PeriodOfTime #line:White
AssignmentRule_ -right- AssignmentRule__ #line:White
Entity -right- _Role #line:White

class Authorisation #LightYellow;line:DarkRed;text:DarkRed
class Law #LightYellow;line:DarkRed;text:DarkRed
class Scope #LightYellow;line:DarkRed;text:DarkRed
class Document #LightYellow;line:DarkRed;text:DarkRed
class [ABS]LegalBasis #LightYellow;line:DarkRed;text:DarkRed
class IdentificationDocument #LightYellow;line:DarkRed;text:DarkRed
class EconomicOperator #LightYellow;line:DarkRed;text:DarkRed
class Involvement #LightYellow;line:DarkRed;text:DarkRed
class Role #LightYellow;line:DarkRed;text:DarkRed
class Person #LightYellow;line:DarkRed;text:DarkRed
class Machine #LightYellow;line:DarkRed;text:DarkRed
class AssignmentRule #LightYellow;line:DarkRed;text:DarkRed
class Restriction #LightYellow;line:DarkRed;text:DarkRed
class Entity #LightYellow;line:DarkRed;text:DarkRed
class PeriodOfTime #LightYellow;line:DarkRed;text:DarkRed

class eService #CEEED0;line:285F17;text:285F17
class ISO4217:20215 #CEEED0;line:285F17;text:285F17
class NACE #CEEED0;line:285F17;text:285F17
class SpacialExtent #CEEED0;line:285F17;text:285F17
class identificationDocumentType #CEEED0;line:285F17;text:285F17
class ISO80000Unit #CEEED0;line:285F17;text:285F17
class ISO80000-2 #CEEED0;line:285F17;text:285F17
class NumericValue #CEEED0;line:285F17;text:285F17
class Unit #CEEED0;line:285F17;text:285F17

hide circle

@enduml
