classDiagram
    direction LR
%% =========================
%% Core EBW Classes
%% =========================
    class CredentialSubject {
        <<EBW>>
    }

    class BankAccount {
        <<EBW>>
        +accountName: string
        +accountType: string
        +iban: Iban
        +owner: Company
        +provider: Company
    }

    class Company {
        identifier: List
    }

    class Bic

    class Iban

    class ClearingNumber

%% =========================
%% External / Referenced Types
%% =========================

%% =========================
%% Inheritance
%% =========================
    CredentialSubject <|-- BankAccount

%% =========================
%% Properties (Object relations)
%% =========================
    BankAccount --> Company: owner
    BankAccount --> Company: provider
    BankAccount --> Iban : iban
    Company --> Bic : identifier
    Company --> ClearingNumber : identifier
