classDiagram
    direction LR
%% =========================
%% Core EBW Classes
%% =========================
    class ElectronicAttestationOfAttributes {
        <<EBW>>
        +attestationLegalCategory: AttestationLegalCategory
    }

%% =========================
%% External / Referenced Types
%% =========================
    class VerifiableCredential {
        <<external>>
    }

%% =========================
%% Inheritance
%% =========================
    VerifiableCredential <|-- ElectronicAttestationOfAttributes

%% =========================
%% Properties (Object relations)
%% =========================
