classDiagram
    direction LR
%% =========================
%% Core EBW Classes
%% =========================
    class CredentialSubject {
        <<EBW>>
    }

    class Company {
        <<EBW>>
        +legalName: string
        +legalForm: string
        +legalIdentifier: Euid
        +activity: Nace21
        +identifier: List<string>
        +registeredAddress: Address
        +correspondenceAddress: Address
        +dateOfRegistration: date
        +legalStatus: string
        +lei: string
        +vat: string
        +tin: string
        +lei: string
        +eori: string
        +excise: string
    }

    class NaturalPerson {
        <<EBW>>
        +givenName: string
        +familyName: string
        +birthDate: date
    }

    class LegalPerson {
        <<EBW>>
        +legalName: string
        +legalForm: string
        +legalIdentifier: Euid
    }

    class LimitedLiabilityCompany {
        <<EBW>>
        +legalRepresentative: NaturalPerson
        +subscribedCapital: Capital
    }

    class Partnership {
        <<EBW>>
        +partner: GeneralPartner, LimitedPartner
    }

    class GeneralPartner {
        <<EBW>>
        +partnerId: NaturalPerson, LegalPerson
    }

    class LimitedPartner {
        <<EBW>>
        +partnerId: NaturalPerson, LegalPerson
        +liabilityOrContribution: Capital
    }

    class LegalRepresentative {
        <<EBW>>
        +legalRepresentativeId: uri
        +role: string
        +scopeOfAuthorization: ScopeOfAuthorization
    }


%% =========================
%% External / Referenced Types
%% =========================

%% =========================
%% Inheritance
%% =========================
    CredentialSubject <|-- NaturalPerson
    CredentialSubject <|-- LegalPerson
    CredentialSubject <|-- Company
    Company <|-- LimitedLiabilityCompany
    Company <|-- Partnership

%% =========================
%% Properties (Object relations)
%% =========================
    LegalRepresentative --> NaturalPerson: legalRepresentativeId
    LegalRepresentative --> LegalPerson: legalRepresentativeId
    LimitedLiabilityCompany --> LegalRepresentative: legalRepresentative
    Partnership --> GeneralPartner: partner
    Partnership --> LimitedPartner: partner
    GeneralPartner --> NaturalPerson: partnerId
    GeneralPartner --> LegalPerson: partnerId
    LimitedPartner --> NaturalPerson: partnerId
    LimitedPartner --> LegalPerson: partnerId
